//env.SHARED_LIB_TAG should be injected from (Folder) environment properties
env.SHARED_LIB_TAG="main"
library identifier: "ci-shared-library@${env.SHARED_LIB_TAG}", retriever: modernSCM(
        [$class: 'GitSCMSource',
         remote: 'https://github.com/cb-ci-templates/ci-shared-library.git'])

def pod = libraryResource 'podtemplates/podTemplate-curl.yaml'

// Uses Declarative syntax to run commands inside a container.
pipeline {
    agent {
        kubernetes {
            defaultContainer "custom-agent"
            yaml pod
        }
    }
    stages {
        stage('Stage1') {
            steps {
                sh 'hostname'
                helloWorld "${firstname}"
                helloWorld "${lastname}"
            }
        }
        stage('Stage2') {
            steps {
                sh 'hostname'
                helloWorld "${firstname}"
                helloWorld "${lastname}"
            }
        }
    }
}
