library identifier: 'custom-lib@master', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: 'git@github.com:cb-ci-templates/ci-shared-library.git',
   credentialsId: 'github-user-ssh'])

def agentPod = libraryResource 'podtemplates/podTemplate-curl.yaml'
def testName="TESTNAME"
// Uses Declarative syntax to run commands inside a container.
pipeline {
    agent {
        kubernetes {
            defaultContainer "custom-agent"
            yaml agentPod
        }
    }
    stages {
        stage('Hello') {
            steps {
                sh 'hostname'
                helloWorld "${firstname}"
                helloWorld "${testName}"
            }
        }
    }
}
