library identifier: 'ci-shared-library@main', retriever: modernSCM(
        [$class: 'GitSCMSource',
         remote: 'https://github.com/cb-ci-templates/ci-shared-library.git'])
library identifier: 'ci-shared-library_pt@main', retriever: modernSCM(
        [$class: 'GitSCMSource',
         remote: 'https://github.com/cb-ci-templates/ci-shared-library-pt.git'])

// Building the data object
def configYaml = """---
app : 'Hello World'
k8_agent_yaml : ${k8_agent_yaml}
firstName: ${firstName}
lastName: ${lastName}
"""
Map configMap = readYaml text: "${configYaml}"

pt_ci_sample_helloworld (configMap)