// Uses Declarative syntax to run commands inside a container.
pipeline {
    agent none
    stages {
        stage('Stage hello') {
            steps {
                helloWorld "${firstname}"
                helloWorld "${lastname}"
            }
        }
    }
}

/**
helloWorld sample step
Should be in a Shared Library
param: name to print to console, no agent context required
*/
def helloWorld(name){
    echo "${name}"
}
