// Uses Declarative syntax to run commands inside a container.
pipeline {
    agent none
    stages {
        stage('Stage hello') {
            steps {
               echo "HellowWorld"
            }
        }
    }
}

