//env.SHARED_LIB_TAG should be injected from (Folder) environment properties
env.SHARED_LIB_TAG=main

library identifier: "ci-shared-library@${env.SHARED_LIB_TAG}", retriever: modernSCM(
        [$class: 'GitSCMSource',
         remote: 'https://github.com/cb-ci-templates/ci-shared-library.git'])
library identifier: "ci-shared-library_pt@${env.SHARED_LIB_TAG}", retriever: modernSCM(
        [$class: 'GitSCMSource',
         remote: 'https://github.com/cb-ci-templates/ci-shared-library-pt.git'])




// Building the data object
def configYaml = """---
k8_agent_yaml : "podTemplate-simple.yaml"
branchPropertiesFile: "ci-config.properties"
param_greetings : 'Greetings to the rest of the World!'
"""


//Create a pipelineParams Map for the Pipeline template below
Map pipelineParams = readYaml text: "${configYaml}"
println pipelineParams

//###### START PIPELINE TEMPLATE###########
//We call the template from ci_shared_library_pt
pt_ci_simple (pipelineParams)
