#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: tools-pv
#spec:
#  capacity:
#    storage: 1Gi
#  storageClassName: zonal-rwx
#  accessModes:
#    - ReadWriteMany
#  csi:
#    driver: filestore.csi.k8s.io
#    volumeHandle: projects/acaternberg/locations/us-east1-d/instances/my-filestore-instance  # Adjust as needed
#  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tools-pvc
spec:
  storageClassName: zonal-rwx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: tools-pod
spec:
  containers:
    - name: amazonlinux
      image: amazonlinux
      command: ["sh", "-c", "while true; do echo hello; sleep 10; done"]
      volumeMounts:
        - mountPath: /tools
          name: tools-volume
  volumes:
    - name: tools-volume
      persistentVolumeClaim:
        claimName: tools-pvc
